environments:
  # The "default" environment is available and used when `helmfile` is run without `--environment NAME`.
  #
  # these values are available to any values.yaml.gotmpl files but they are not passed into 
  # the helm charts directly
  default:
    values:
    - jx-values.yaml
    - versionStream/src/fake-secrets.yaml.gotmpl
releases:
- chart: jenkins-x/jxboot-helmfile-resources
- chart: external-secrets/kubernetes-external-secrets
- chart: jx-labs/jenkins-x-crds
- chart: jx3/jx-preview
- chart: stable/nginx-ingress
- chart: jenkins-x/tekton
- chart: jenkins-x/lighthouse
- chart: jenkins-x/nexus
- chart: jenkins-x/chartmuseum
- chart: banzaicloud-stable/vault-operator
- chart: jx-labs/vault-instance
- chart: jx-labs/pusher-wave
repositories:
- name: jenkins-x
  url: https://storage.googleapis.com/chartmuseum.jenkins-x.io
- name: external-secrets
  url: https://godaddy.github.io/kubernetes-external-secrets
- name: jx-labs
  url: https://storage.googleapis.com/jenkinsxio-labs-private/charts
- name: stable
  url: https://kubernetes-charts.storage.googleapis.com
- name: banzaicloud-stable
  url: https://kubernetes-charts.banzaicloud.com
- name: jx3
  url: https://storage.googleapis.com/jenkinsxio/charts
